"""
hooks.py — Master Wiring File
===============================
Connects all TOC automation to the Frappe/ERPNext lifecycle.
"""

app_name = "chaizup_toc"
app_title = "Chaizup TOC"
app_publisher = "Chaizup"
app_description = "Theory of Constraints Buffer Management — replaces default Auto Material Request with BP%-driven replenishment"
app_email = "tech@chaizup.com"
app_license = "MIT"
required_apps = ["frappe", "erpnext"]
app_version = "1.0.0"

# ═══════════════════════════════════════════════════════
# BRANDING & LOGO
# app_logo_url   → used in Frappe app switcher + printed docs
# app_icon       → fallback octicon for older Frappe UI
# app_color      → tile background colour on Desk home
# ═══════════════════════════════════════════════════════
app_logo_url = "/assets/chaizup_toc/images/chaizup_toc_logo.svg"
app_icon     = "graph"
app_color    = "#E67E22"

# ═══════════════════════════════════════════════════════
# FRAPPE DESK HOME — App Switcher (9-dot grid icon)
# Registers Chaizup TOC as a clickable tile on the
# Frappe apps home screen so users can launch it from
# any module — same as ERPNext, Manufacturing, etc.
# ═══════════════════════════════════════════════════════
add_to_apps_screen = [
    {
        "name":           "chaizup_toc",
        "logo":           "/assets/chaizup_toc/images/chaizup_toc_logo.svg",
        "title":          "Chaizup TOC",
        "route":          "/app/toc-dashboard",
        "has_permission": "chaizup_toc.api.permissions.has_app_permission",
    }
]

# ═══════════════════════════════════════════════════════
# INSTALLATION HOOKS
# On install: disables default ERPNext auto reorder
# On uninstall: re-enables it (safety net)
# ═══════════════════════════════════════════════════════
after_install = "chaizup_toc.setup.install.after_install"
before_uninstall = "chaizup_toc.setup.install.before_uninstall"

# ═══════════════════════════════════════════════════════
# SCHEDULED JOBS — Daily Operating Rhythm
# ═══════════════════════════════════════════════════════
scheduler_events = {
    "cron": {
        # ── 06:30 AM Daily: ADU Auto-Calculate (R1/R4) ──
        # Calculates Average Daily Usage for all TOC items
        # SKIPS items where "Custom ADU [TOC App]" is checked
        # Reads Delivery Notes (FG) / Stock Entries (RM/PM/SFG)
        "30 6 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_adu_update"
        ],
        # ── 07:00 AM Daily: Production Priority Run ──
        # Calculates all FG buffers, generates MRs for Red/Yellow
        "0 7 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_production_run"
        ],
        # ── 07:30 AM Daily: Procurement Monitoring Run ──
        # Calculates all RM/PM buffers, logs warning for Red/Black items.
        # MRs for RM/PM are already generated by the 07:00 AM production run
        # (which runs generate_material_requests() with no buffer_type filter).
        "30 7 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_procurement_run"
        ],
        # ── 08:00 AM Daily: Buffer Snapshot Logging ──
        # Logs all buffer states for DBM analysis
        "0 8 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_buffer_snapshot"
        ],
        # ── 08:00 AM Sunday: Weekly DBM Evaluation ──
        # Checks TMR/TMG triggers, auto-adjusts buffers
        "0 8 * * 0": [
            "chaizup_toc.tasks.daily_tasks.weekly_dbm_check"
        ],
    }
}

# ═══════════════════════════════════════════════════════
# DOC EVENTS — Real-Time Buffer Monitoring
# ═══════════════════════════════════════════════════════
doc_events = {
    # Stock movement → re-check affected buffer
    "Stock Ledger Entry": {
        "after_insert": "chaizup_toc.toc_engine.buffer_calculator.on_stock_movement"
    },
    # Sales Order submit/cancel → reserved_qty changes → FG buffer impact
    "Sales Order": {
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_demand_change",
        "on_cancel": "chaizup_toc.toc_engine.buffer_calculator.on_demand_change",
    },
    # Work Order changes → WIP changes → FG buffer impact
    "Work Order": {
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        "on_cancel": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        "on_update_after_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
    },
    # Purchase Order → on_order changes → RM buffer impact
    "Purchase Order": {
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        "on_cancel": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
    },
    # Material Request validation — block manual MR if TOC is active
    "Material Request": {
        "validate": "chaizup_toc.overrides.material_request.validate_toc_compliance",
    },
    # Item validate — auto-calc target buffer when TOC fields change
    "Item": {
        "validate": "chaizup_toc.overrides.item.on_item_validate",
    },
    # NOTE: TOC Item Buffer calculations (F1/F6/zone thresholds) are handled
    # entirely by TOCItemBuffer.validate() in the controller. No doc_event needed.
}

# ═══════════════════════════════════════════════════════
# FIXTURES — Custom Fields on built-in DocTypes
# ═══════════════════════════════════════════════════════
fixtures = [
    {
        "doctype": "Custom Field",
        "filters": [["module", "=", "Chaizup Toc"]]
    },
    {
        "doctype": "Property Setter",
        "filters": [["module", "=", "Chaizup Toc"]]
    },
]

# ═══════════════════════════════════════════════════════
# CLIENT-SIDE JS OVERRIDES
# ═══════════════════════════════════════════════════════
doctype_js = {
    "Item": "public/js/item_toc.js",
    "Material Request": "public/js/material_request_toc.js",
    "Stock Entry": "public/js/stock_entry_toc.js",
}

# ═══════════════════════════════════════════════════════
# APP-LEVEL CSS
# ═══════════════════════════════════════════════════════
# ═══════════════════════════════════════════════════════
# DESK ASSETS — loaded on every Frappe Desk page
# chaizup_toc.bundle.js: navbar logo, app tile branding,
#   zone colours in list views, workspace icon injection
# toc.css: global TOC styling across all DocType forms
# ═══════════════════════════════════════════════════════
app_include_js  = ["/assets/chaizup_toc/js/desk_branding.js"]
app_include_css = "/assets/chaizup_toc/css/toc.css"

# ═══════════════════════════════════════════════════════
# OVERRIDE DEFAULT AUTO REORDER
# Prevents the built-in reorder_item scheduler from running
# even if someone accidentally re-enables the Stock Setting
# ═══════════════════════════════════════════════════════
override_whitelisted_methods = {
    "erpnext.stock.reorder_item.reorder_item": "chaizup_toc.overrides.reorder_override.toc_reorder_item"
}

# ═══════════════════════════════════════════════════════
# PERMISSION QUERY — Role-based buffer visibility
# ═══════════════════════════════════════════════════════
has_permission = {
    "TOC Buffer Log": "chaizup_toc.api.permissions.has_buffer_log_permission",
}

# ═══════════════════════════════════════════════════════
# JINJA METHODS — Available in Print Formats
# ═══════════════════════════════════════════════════════
jinja = {
    "methods": [
        "chaizup_toc.toc_engine.buffer_calculator.get_zone_color",
        "chaizup_toc.toc_engine.buffer_calculator.get_zone_label",
    ]
}

# ═══════════════════════════════════════════════════════
# WEBSITE
# ═══════════════════════════════════════════════════════
website_route_rules = [
    # /toc-guide → serves the toc-user-guide.html www page
    {"from_route": "/toc-guide", "to_route": "toc-user-guide"},
    # Direct access also works at /toc-user-guide (matches www/toc-user-guide.html)
]
