"""
hooks.py — Master Wiring File
===============================
Connects all TOC automation to the Frappe/ERPNext lifecycle.
"""

app_name = "chaizup_toc"
app_title = "Chaizup TOC"
app_publisher = "Chaizup"
app_description = "Theory of Constraints Buffer Management — replaces default Auto Material Request with BP%-driven replenishment"
app_email = "tech@chaizup.com"
app_license = "MIT"
required_apps = ["frappe", "erpnext"]
app_version = "1.0.0"

# ═══════════════════════════════════════════════════════
# BRANDING & LOGO
# app_logo_url   → used in Frappe app switcher + printed docs
# app_icon       → fallback octicon for older Frappe UI
# app_color      → tile background colour on Desk home
# ═══════════════════════════════════════════════════════
app_logo_url = "/assets/chaizup_toc/images/chaizup_toc_logo.svg"
app_icon     = "graph"
app_color    = "#E67E22"

# ═══════════════════════════════════════════════════════
# FRAPPE DESK HOME — App Switcher (9-dot grid icon)
# Registers Chaizup TOC as a clickable tile on the
# Frappe apps home screen so users can launch it from
# any module — same as ERPNext, Manufacturing, etc.
# ═══════════════════════════════════════════════════════
add_to_apps_screen = [
    {
        "name":           "chaizup_toc",
        "logo":           "/assets/chaizup_toc/images/chaizup_toc_logo.svg",
        "title":          "Chaizup TOC",
        "route":          "/app/toc-dashboard",
        "has_permission": "chaizup_toc.api.permissions.has_app_permission",
    }
]

# ═══════════════════════════════════════════════════════
# INSTALLATION HOOKS
# On install: disables default ERPNext auto reorder
# On uninstall: re-enables it (safety net)
# ═══════════════════════════════════════════════════════
after_install = "chaizup_toc.setup.install.after_install"
before_uninstall = "chaizup_toc.setup.install.before_uninstall"

# 2026-05-19 — after_migrate runs on every `bench migrate`. We use it to
# back-fill the TOC UOM custom fields on existing Work Orders, Production
# Plans, and BOMs whenever the schema has been updated (the function is
# idempotent — already-stamped rows are skipped). MRP is intentionally
# left untouched.
after_migrate = "chaizup_toc.setup.install.after_migrate"

# ═══════════════════════════════════════════════════════
# SCHEDULED JOBS — Daily Operating Rhythm
# ═══════════════════════════════════════════════════════
scheduler_events = {
    "cron": {
        # ── 12:00 AM Daily: Min Order Qty Sync ──
        # Syncs Item Min Order Qty (purchase) from Item.minimum_order_qty field.
        # Syncs Item Minimum Manufacture (manufacture) from WO history for items with no rows.
        # Sends email alert for any items still missing min order qty config.
        "0 0 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_min_order_sync"
        ],
        # ── 02:00 AM Daily: Sales Projection → Production Plan Automation ──
        # Finds all submitted Sales Projections for the current month (one per warehouse).
        # Calculates warehouse-specific demand shortage per item and creates Draft
        # Production Plans. Runs before ADU (06:30) so new PPs are visible in daily calcs.
        # Two scenarios: Calc 1 (forecast exists) and Calc 2 (0 forecast but SOs pending).
        "0 2 * * *": [
            "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.daily_production_plan_automation"
        ],
        # ── 06:30 AM Daily: ADU Auto-Calculate (R1/R4) ──
        # Calculates Average Daily Usage for all TOC items
        # SKIPS items where "Custom ADU [TOC App]" is checked
        # Reads Delivery Notes (FG) / Stock Entries (RM/PM/SFG)
        "30 6 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_adu_update"
        ],
        # ── 06:35 AM Daily: Item Minimum Manufacture ADU + Max Level refresh (IMM-002) ──
        # Runs 5 minutes after daily_adu_update so the per-Item ADU writer
        # is finished. Per-warehouse ADU read directly from SLE outflows.
        # Updates adu, adu_lookback_days, max_level, last_updated_on on
        # every Item Minimum Manufacture row with a warehouse set.
        "35 6 * * *": [
            "chaizup_toc.tasks.daily_tasks.update_min_mfg_adu_levels"
        ],
        # ── 07:00 AM Daily: Production Priority Run ──
        # Calculates all FG buffers, generates MRs for Red/Yellow
        "0 7 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_production_run"
        ],
        # ── 07:30 AM Daily: Procurement Monitoring Run ──
        # Calculates all RM/PM buffers, logs warning for Red/Black items.
        # MRs for RM/PM are already generated by the 07:00 AM production run
        # (which runs generate_material_requests() with no buffer_type filter).
        "30 7 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_procurement_run"
        ],
        # ── 08:00 AM Daily: Buffer Snapshot Logging ──
        # Logs all buffer states for DBM analysis
        "0 8 * * *": [
            "chaizup_toc.tasks.daily_tasks.daily_buffer_snapshot"
        ],
        # ── 09:00 AM Sunday: Weekly DBM Evaluation ──
        # Runs 1 hour after daily_buffer_snapshot (08:00 AM) to ensure
        # today's log entries are committed before DBM reads them.
        "0 9 * * 0": [
            "chaizup_toc.tasks.daily_tasks.weekly_dbm_check"
        ],
    }
}

# ═══════════════════════════════════════════════════════
# DOC EVENTS — Real-Time Buffer Monitoring
# ═══════════════════════════════════════════════════════
doc_events = {
    # Stock movement → re-check affected buffer
    "Stock Ledger Entry": {
        "after_insert": "chaizup_toc.toc_engine.buffer_calculator.on_stock_movement"
    },
    # 2026-05-19 — Production entry → refresh WO + PP produced-qty mirror.
    # Manufacture-purpose Stock Entries write WO.produced_qty via direct
    # frappe.db.set_value calls (inside Work Order.update_status), which
    # bypasses validate. The hook below catches this and recomputes
    # custom_produced_qty_in_uom on both the WO and the parent PP row.
    "Stock Entry": {
        "on_submit": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.on_stock_entry_submit_refresh_produced",
        "on_cancel": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.on_stock_entry_submit_refresh_produced",
    },
    # Sales Order submit/cancel → reserved_qty changes → FG buffer impact
    "Sales Order": {
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_demand_change",
        "on_cancel": "chaizup_toc.toc_engine.buffer_calculator.on_demand_change",
    },
    # Work Order changes → WIP changes → FG buffer impact
    "Work Order": {
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        # v0.0.17 — on_cancel chained list: buffer recompute first, then
        # BOM count refresh. Frappe iterates the list in order.
        "on_cancel": [
            "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
            "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.refresh_bom_wo_count_for_wo",
        ],
        "on_update_after_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        # 2026-05-19 — bidirectional UOM sync: recompute custom_uom/CF/
        # custom_qty_in_uom from the standard `qty` field. Catches
        # programmatic writes that don't go through the JS controller.
        "validate":  "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.stamp_uom_fields_on_wo_validate",
        # 2026-05-27 (v0.0.17) — sync BOM.custom_wo_count after WO state
        # changes. Hooked on after_insert / on_cancel / on_trash.
        # Idempotent — recomputes from a SELECT COUNT(*), never just +/-1.
        # The on_cancel hook list below registers TWO handlers; Frappe
        # accepts a list and calls each in order.
        "after_insert": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.refresh_bom_wo_count_for_wo",
        "on_trash":     "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.refresh_bom_wo_count_for_wo",
    },
    # Purchase Order → on_order changes → RM buffer impact
    # before_insert → copy TOC metadata from source Material Request (if TOC-generated)
    "Purchase Order": {
        "before_insert": "chaizup_toc.overrides.purchase_order.on_purchase_order_before_insert",
        "on_submit": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
        "on_cancel": "chaizup_toc.toc_engine.buffer_calculator.on_supply_change",
    },
    # Material Request validation — block manual MR if TOC is active
    "Material Request": {
        "validate": "chaizup_toc.overrides.material_request.validate_toc_compliance",
    },
    # Item validate — auto-calc target buffer when TOC fields change
    "Item": {
        "validate": "chaizup_toc.overrides.item.on_item_validate",
    },
    # Sales Projection — notify configured users on edit and submit
    # on_update fires after every save; the handler gates on docstatus==0 to
    # avoid double-notification (on_update also fires after on_submit).
    "Sales Projection": {
        "on_update": "chaizup_toc.chaizup_toc.toc_engine.projection_engine.on_sales_projection_update",
        "on_submit": "chaizup_toc.chaizup_toc.toc_engine.projection_engine.on_sales_projection_submit",
    },
    # Production Plan — auto-set custom_created_by = "User" for manually created plans.
    # The automation pre-sets "System" before insert; this hook only fires for blank field.
    #
    # before_cancel: severs `Sales Projected Items.wo_name` references to this PP
    # before Frappe's back-link guard fires. This is the PP-side half of the SP↔PP
    # circular-cancel deadlock fix (the SP side lives in SalesProjection.before_cancel,
    # which uses self.flags.ignore_links = True). See production_plan_engine.py for the
    # full reasoning + DANGER/RESTRICT notes.
    "Production Plan": {
        "before_insert": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.on_production_plan_before_insert",
        "before_cancel": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.on_production_plan_before_cancel",
        # 2026-05-19 — auto-populate TOC UOM custom fields on every save.
        # Idempotent (respects user-picked custom_uom; only auto-fills when
        # blank). Recomputes the in-UOM displays from the standard qty
        # fields so the row stays in sync after ERPNext writes (BOM
        # explosion, "Get Sub-Assemblies" button, scheduler back-fills).
        # See production_plan_engine.stamp_uom_fields_on_pp_validate.
        "validate":      "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.stamp_uom_fields_on_pp_validate",
    },
    # NOTE: TOC Item Buffer calculations (F1/F6/zone thresholds) are handled
    # entirely by TOCItemBuffer.validate() in the controller. No doc_event needed.
    #
    # 2026-05-19 — BOM bidirectional UOM sync. Recomputes custom_uom/CF/
    # custom_qty_in_uom from the standard `quantity` field on every save.
    "BOM": {
        "validate": "chaizup_toc.chaizup_toc.toc_engine.production_plan_engine.stamp_uom_fields_on_bom_validate",
    },
}

# ═══════════════════════════════════════════════════════
# FIXTURES — Custom Fields on built-in DocTypes
# ═══════════════════════════════════════════════════════
fixtures = [
    {
        "doctype": "Custom Field",
        "filters": [["module", "=", "Chaizup Toc"]]
    },
    {
        "doctype": "Property Setter",
        "filters": [["module", "=", "Chaizup Toc"]]
    },
    # 2026-05-19 — List View Settings for ERPNext doctypes we want to ship
    # opinionated default columns for. The doctype has no `module` field, so
    # we filter by name (one row per doctype, singleton-style). Adding new
    # entries here means installs/migrations get the same list-view defaults
    # as the live dev site.
    #
    # Restricted: only doctypes that chaizup_toc actually customises. Do NOT
    # add unrelated doctypes here — those should stay user-customisable.
    {
        "doctype": "List View Settings",
        "filters": [["name", "in", ["Work Order", "BOM"]]],
    },
]

# ═══════════════════════════════════════════════════════
# CLIENT-SIDE JS OVERRIDES
# ═══════════════════════════════════════════════════════
doctype_js = {
    "Item": "public/js/item_toc.js",
    "Material Request": "public/js/material_request_toc.js",
    "Stock Entry": "public/js/stock_entry_toc.js",
    "Work Order":      "public/js/work_order_mrp_uom.js",
    "Production Plan": "public/js/production_plan_mrp_uom.js",
    "BOM":             "public/js/bom_uom.js",
}

# 2026-05-19 — List-view extras: merge framework audit columns
# (creation / owner / modified / modified_by) into the existing ERPNext
# `frappe.listview_settings[doctype].add_fields` arrays so they appear
# as default columns in Report View. These files load AFTER ERPNext's
# `<dt>_list.js` (Frappe loads by app dependency order) and concat into
# the existing arrays instead of overwriting — preserving the ERPNext
# status indicators that depend on the original `add_fields` entries.
doctype_list_js = {
    "Work Order": "public/js/work_order_list_extras.js",
    "BOM":        "public/js/bom_list_extras.js",
}

# ═══════════════════════════════════════════════════════
# APP-LEVEL CSS
# ═══════════════════════════════════════════════════════
# ═══════════════════════════════════════════════════════
# DESK ASSETS — loaded on every Frappe Desk page
# chaizup_toc.bundle.js: navbar logo, app tile branding,
#   zone colours in list views, workspace icon injection
# toc.css: global TOC styling across all DocType forms
# ═══════════════════════════════════════════════════════
app_include_js  = ["/assets/chaizup_toc/js/desk_branding.js"]
app_include_css = "/assets/chaizup_toc/css/toc.css"

# ═══════════════════════════════════════════════════════
# OVERRIDE DEFAULT AUTO REORDER
# Prevents the built-in reorder_item scheduler from running
# even if someone accidentally re-enables the Stock Setting
# ═══════════════════════════════════════════════════════
override_whitelisted_methods = {
    "erpnext.stock.reorder_item.reorder_item": "chaizup_toc.overrides.reorder_override.toc_reorder_item"
}

# ═══════════════════════════════════════════════════════
# OVERRIDE DOCTYPE CLASS — Production Plan
# 2026-05-19 — Wires ChaizupProductionPlan so the standard
# "Get Sub Assembly Items" button stamps the TOC UOM custom
# fields (custom_uom, custom_uom_conversion_factor,
# custom_required_qty_in_uom, custom_projected_qty_in_uom,
# custom_qty_to_order_in_uom) immediately when sub-assembly
# rows are fetched — not only on Save.
#
# Closes the gap left by the validate-only path: the JS
# child events don't fire on bulk row insertion from
# `frm.call("get_sub_assembly_items", doc: frm.doc)`, so
# without this override the in-UOM columns stayed at 0
# until the user clicked Save.
#
# See: chaizup_toc/overrides/production_plan.py
# ═══════════════════════════════════════════════════════
override_doctype_class = {
    "Production Plan": "chaizup_toc.overrides.production_plan.ChaizupProductionPlan",
}

# ═══════════════════════════════════════════════════════
# PERMISSION QUERY — Role-based buffer visibility
# ═══════════════════════════════════════════════════════
has_permission = {
    "TOC Buffer Log": "chaizup_toc.api.permissions.has_buffer_log_permission",
}

# ═══════════════════════════════════════════════════════
# JINJA METHODS — Available in Print Formats
# ═══════════════════════════════════════════════════════
jinja = {
    "methods": [
        "chaizup_toc.toc_engine.buffer_calculator.get_zone_color",
        "chaizup_toc.toc_engine.buffer_calculator.get_zone_label",
    ]
}

# ═══════════════════════════════════════════════════════
# WEBSITE
# ═══════════════════════════════════════════════════════
website_route_rules = [
    # /toc-guide → serves the toc-user-guide.html www page
    {"from_route": "/toc-guide", "to_route": "toc-user-guide"},
    # Direct access also works at /toc-user-guide (matches www/toc-user-guide.html)
]
