"""
Material Request Override — TOC Compliance
============================================
Warns users if they manually create MRs for TOC-managed items.
Does NOT block — just informs.
"""

import frappe
from frappe import _


def validate_toc_compliance(doc, method):
    """Warn if manually creating MR for a TOC-managed item."""
    if doc.custom_toc_recorded_by == "By System":
        return  # Auto-generated by TOC — no warning needed

    toc_items = []
    for item in doc.items:
        if frappe.db.get_value("Item", item.item_code, "custom_toc_enabled"):
            toc_items.append(item.item_code)

    if toc_items:
        frappe.msgprint(
            msg=_(
                "<b>TOC Notice:</b> The following items are managed by TOC Buffer Management: "
                f"<br><b>{', '.join(toc_items)}</b><br><br>"
                "The TOC system auto-generates Material Requests daily at 7:00 AM based on "
                "Buffer Penetration %. Manual MRs may conflict with TOC calculations.<br><br>"
                "Formula: <b>F4: Order Qty = Target Buffer − Inventory Position</b>"
            ),
            title=_("TOC Managed Items Detected"),
            indicator="orange",
        )
